version: '3.8'

services:
    postgres:
        image: postgres:16
        environment:
            POSTGRES_USER_FILE: /run/secrets/postgres_user
            POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
            POSTGRES_DB_FILE: /run/secrets/postgres_db
        secrets:
            - postgres_user
            - postgres_password
            - postgres_db
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ../docker/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

secrets:
    postgres_user:
        file: ./secrets/postgres_user.txt
    postgres_password:
        file: ./secrets/postgres_password.txt
    postgres_db:
        file: ./secrets/postgres_db.txt

volumes:
    pgdata:
