-- =============================================================================
-- ForeFront — database initialisation script
-- Executed automatically by PostgreSQL on first container start.
-- Re-running is safe: all statements use IF NOT EXISTS.
-- =============================================================================

-- ---------------------------------------------------------------------------
-- orders
-- Stores one row per customer order.
-- order_id  : application-generated GUID (text)
-- kund_id   : reference to the customer who placed the order
-- status    : stored as a human-readable string matching the OrderStatus enum
--             (Pending | Confirmed | Shipped | Delivered | Cancelled)
-- created   : UTC timestamp set by the application at creation time
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    order_id   TEXT         NOT NULL,
    kund_id    TEXT         NOT NULL,
    status     VARCHAR(20)  NOT NULL DEFAULT 'Pending',
    created    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT pk_orders PRIMARY KEY (order_id),
    CONSTRAINT chk_orders_status CHECK (
        status IN ('Pending', 'Confirmed', 'Shipped', 'Delivered', 'Cancelled')
    )
);

-- ---------------------------------------------------------------------------
-- order_lines
-- Stores one row per product line within an order.
-- order_line_id : surrogate GUID generated by the application
-- order_id      : foreign key ? orders.order_id (CASCADE delete)
-- produkt_id    : product catalogue reference
-- namn          : product name captured at order time (denormalised)
-- antal         : quantity ordered
-- pris          : unit price captured at order time (denormalised)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_lines (
    order_line_id  TEXT            NOT NULL,
    order_id       TEXT            NOT NULL,
    produkt_id     TEXT            NOT NULL,
    namn           TEXT            NOT NULL,
    antal          INTEGER         NOT NULL CHECK (antal > 0),
    pris           NUMERIC(18, 2)  NOT NULL CHECK (pris > 0),

    CONSTRAINT pk_order_lines    PRIMARY KEY (order_line_id),
    CONSTRAINT fk_order_lines_order
        FOREIGN KEY (order_id)
        REFERENCES orders (order_id)
        ON DELETE CASCADE
);

-- ---------------------------------------------------------------------------
-- Indexes
-- ---------------------------------------------------------------------------

-- Speeds up GetAll / status-filtered queries used by WarehouseService
CREATE INDEX IF NOT EXISTS ix_orders_status
    ON orders (status);

-- Speeds up date-range filtering used by GetVolumes / GetTopProducts
CREATE INDEX IF NOT EXISTS ix_orders_created
    ON orders (created);

-- Speeds up joining order_lines back to their parent order
CREATE INDEX IF NOT EXISTS ix_order_lines_order_id
    ON order_lines (order_id);

-- Speeds up volume aggregation GROUP BY produkt_id
CREATE INDEX IF NOT EXISTS ix_order_lines_produkt_id
    ON order_lines (produkt_id);
