using ForeFrontWebApplication.Models.Order;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ForeFrontWebApplication.Data.Configurations;

public sealed class OrderLineConfiguration : IEntityTypeConfiguration<OrderLine>
{
    public void Configure(EntityTypeBuilder<OrderLine> builder)
    {
        builder.ToTable("order_lines");

        // Surrogate PK — generated by the application before insert
        builder.HasKey(l => l.OrderLineId);

        builder.Property(l => l.OrderLineId)
               .HasColumnName("order_line_id")
               .IsRequired();

        builder.Property(l => l.OrderId)
               .HasColumnName("order_id")
               .IsRequired();

        builder.Property(l => l.ProduktId)
               .HasColumnName("produkt_id")
               .IsRequired();

        builder.Property(l => l.Namn)
               .HasColumnName("namn")
               .IsRequired();

        builder.Property(l => l.Antal)
               .HasColumnName("antal")
               .IsRequired();

        builder.Property(l => l.Pris)
               .HasColumnName("pris")
               .HasPrecision(18, 2)
               .IsRequired();
    }
}
